const section = document.getElementById('choose')
const lh1 = document.getElementById('headerh2')
const header = document.getElementById('header')
const main = document.querySelector('main')
const newRecipes = new Recipes(section, main)
const newBeefIngredientList = new BeefIngredientList(section, lh1, header)
const firstImg = document.getElementById('firstImage')
const secondImg = document.getElementById('secondImage')
const thirdImg = document.getElementById('thirdImage')
const newChickenIngredientList = new ChickenIngredientList(firstImg, secondImg, thirdImg)
const newFishIngredientList = new FishIngredientList(firstImg, secondImg, thirdImg)


// const divContainer = document.createElement('div')
// divContainer.classList.add("container", "h-100")
// const divInner = document.createElement('div')
// divInner.classList.add("container", 'shadow', 'border', 'border-primary', "rounded-lg",)
// const divRowOne = document.createElement('div')
// divRowOne.classList.add("row", "justify-content-center")
// const divRowTwo = document.createElement('div')
// divRowTwo.classList.add("row", "justify-content-center")
// const divRowThree = document.createElement('div')
// divRowThree.classList.add("row", "justify-content-center")
// const divRowFour = document.createElement('div')
// divRowFour.classList.add("row", "justify-content-center")
// const divRowFive = document.createElement('div')
// divRowFive.classList.add("row", "justify-content-center")
// const divRowSix = document.createElement('div')
// divRowSix.classList.add("row", "justify-content-center")
// const imgOne = document.createElement('img')
// imgOne.classList.add('img-thumbnail', 'w-50', 'mt-3', "rounded-lg", 'shadow')
// imgOne.src = 'https://www.thespruceeats.com/thmb/APa5zYrExVw4fDRwChpwQGQuNls=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/marinated-rump-roast-3058682-hero-01-0977a498722f47debaa7034c13053048.jpg'
// const imgTwo = document.createElement('img')
// imgTwo.classList.add('img-thumbnail', 'w-50')
// imgTwo.classList.add('shadow')
// imgTwo.src = 'https://www.maangchi.com/wp-content/uploads/2018/02/roasted-chicken-1.jpg'
// const imgThree = document.createElement('img')
// imgThree.classList.add('img-thumbnail', 'w-50')
// imgThree.classList.add('shadow')
// imgThree.src = 'https://images.immediate.co.uk/production/volatile/sites/2/2018/10/OLI-1018_Everyday-PanFriedCodWithGiantBeanChard_28546-acc2f54.jpg?webp=true&quality=90&crop=20px%2C3414px%2C5444px%2C2342px&resize=556%2C236'
// const h2One = document.createElement('h3')
// h2One.textContent = "Beef"
// const h2Two = document.createElement('h3')
// h2Two.textContent = "Chicken"
// const h2Three = document.createElement('h3')
// h2Three.classList.add("mb-3")
// h2Three.textContent = "Fish"

// main.appendChild(divContainer)
// divContainer.appendChild(divInner)
// divInner.appendChild(divRowOne)
// divRowOne.appendChild(imgOne)
// divInner.appendChild(divRowTwo)
// divRowTwo.appendChild(h2One)
// divInner.appendChild(divRowThree)
// divRowThree.appendChild(imgTwo)
// divInner.appendChild(divRowFour)
// divRowFour.appendChild(h2Two)
// divInner.appendChild(divRowFive)
// divRowFive.appendChild(imgThree)
// divInner.appendChild(divRowSix)
// divRowSix.appendChild(h2Three)



const newApp = new App(newRecipes, newBeefIngredientList, newChickenIngredientList, newFishIngredientList)
newApp.start()
